import { Router } from 'express';
import { userRouter } from './user';
import { classController } from './class';
import { locationRouter } from './location';
import { auth } from '@/middleware/auth';
import { managementRouter } from './management';
import { xmlRouter } from './xml';
import multer from 'multer';
import { bookingRouter } from './booking';
import { blogRouter } from './blog';
import { activityRouter } from './activity';

const router = Router();
const upload = multer();
router.use('/user', userRouter);
router.use('/class', classController);
router.use('/location', locationRouter);
router.use('/blog', blogRouter);
router.use('/activity', activityRouter);
router.use('/booking', auth(['ADMIN', 'TRAINER', 'MEMBER']), bookingRouter);
router.use('/management', auth(['ADMIN', 'TRAINER']), managementRouter);
router.use('/xml', auth(['ADMIN']), upload.single('file'), xmlRouter);
export default router;
